# Generated by Django 5.0.6 on 2026-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='ciphertext',
            field=models.TextField(default=1, verbose_name='Зашифрованный текст (base64)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, verbose_name='Публичный ключ (для E2E-шифрования)'),
        ),
    ]
