# Generated by Django 5.0.6 on 2026-09-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_remove_message_text_message_ciphertext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walk_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='walks.walkstatus')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
